import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import { Providers } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={ptBR}>
    <html lang="en" className={inter.className}>
      <body className="bg-zinc-200 dark:bg-zinc-900">
        <div className="h-screen">
          {/* <Header /> */}

          <div className="py-24 max-w-7xl px-8 mx-auto lg:ml-48">
            <Theme>
            <Providers>{children}</Providers>
            </Theme>
          </div>
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
