import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import Header from "@/components/Header";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-zinc-200 dark:bg-zinc-900">
        <div className="h-screen">
          <Header />

          <div className="py-24 max-w-7xl px-8 mx-auto lg:ml-48">
            <Providers>{children}</Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
